### ISSUE TITLE
Missing model?

### ISSUE THREAD

**Issue by GeorgeFejer91** [deepettas/InhaleSense#4]
You also state that there is a trained model in the data section, but I cannot find one! 
Can you include the model you trained?

**Comment by snousias** [comment]
Thank you for your question, you can find all the data as well as sample implementations of prediction models (including the LSTM model) in the following links:

Code : https://github.com/snousias/Revisiting-Content-Based-Audio-Classification-for-Asthma-Medication-Adherence

Code on IEEE Codeocean : https://codeocean.com/capsule/8383844/tree/

Dataset : https://ieee-dataport.org/documents/respiratory-and-drug-actuation-dataset

The pckl files are not currently available but the process can be easily reproduced and recreate the pckl files through the provided source code.
